### ISSUE TITLE
software unusable if libmagic is not found

### ISSUE THREAD

**Issue by tristan0x** [tristan0x/hpcbench#152]
The feature should be deactivated if native library is not found.

```
$ ben-sh --version
Traceback (most recent call last):
  File "/jenkins/01/workspace/hpc.bb5.canary/platform/tds/hpcbench/venv/bin/ben-sh", line 11, in <module>
    load_entry_point('hpcbench', 'console_scripts', 'ben-sh')()
  File "/jenkins/01/workspace/hpc.bb5.canary/platform/tds/hpcbench/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/jenkins/01/workspace/hpc.bb5.canary/platform/tds/hpcbench/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/jenkins/01/workspace/hpc.bb5.canary/platform/tds/hpcbench/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/jenkins/01/workspace/hpc.bb5.canary/platform/tds/hpcbench/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/jenkins/01/workspace/hpc.bb5.canary/platform/tds/hpcbench/hpcbench/cli/bensh.py", line 26, in <module>
    from hpcbench.driver import CampaignDriver
  File "/jenkins/01/workspace/hpc.bb5.canary/platform/tds/hpcbench/hpcbench/driver.py", line 32, in <module>
    import magic
  File "/jenkins/01/workspace/hpc.bb5.canary/platform/tds/hpcbench/venv/lib/python3.6/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

**Comment by ohm314** [comment]
ah, you're right - on it!

**Comment by tristan0x** [comment]
FYI:
```
$ docker run -ti --rm python:3.6 bash
# python -c 'import ctypes.util ; print(ctypes.util.find_library("magic"))'
libmagic.so.1
# dpkg --purge libtool file libmagic1
# python -c 'import ctypes.util ; print(ctypes.util.find_library("magic"))'
None
```

I suggest to add a unit-test using the `mock` package to make `ctypes.util.find_library` function return `None`

**Comment by tristan0x** [comment]
python-magic will raise an [`ImportError`](https://github.com/ahupp/python-magic/blob/3ca954869ee5f3e55a3d413bea2a90e88387cfe4/magic.py#L183) so adding a `try: except` is IMHO the best you can do.

regarding the tests, UT should detect a change of behavior in python-magic in case the `magic` library is missing. So the test should:

1. Use `mock` library so that `ctypes.util.find_library` return `None`
2. import magic and expect the code the raise an ImportError

**Comment by tristan0x** [comment]
@ohm314 you can take a look at tests/benchmark/test_babelstream.py to see the `@mock.patch` decorator in action.
