### ISSUE TITLE
osu benchmark metric extraction fails in sbatch mode

### ISSUE THREAD

**Issue by ohm314** [tristan0x/hpcbench#170]
```
Traceback (most recent call last):
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/bin/.ben-sh-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/cli/bensh.py", line 47, in main
    driver()
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 280, in __call__
    super(CampaignDriver, self).__call__(**kwargs)
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 96, in _wrapper
    report = dict(children=list(map(str, data)))
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 156, in _call_without_report
    child_obj(**kwargs)
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 96, in _wrapper
    report = dict(children=list(map(str, data)))
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 156, in _call_without_report
    child_obj(**kwargs)
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 96, in _wrapper
    report = dict(children=list(map(str, data)))
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 156, in _call_without_report
    child_obj(**kwargs)
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 96, in _wrapper
    report = dict(children=list(map(str, data)))
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 156, in _call_without_report
    child_obj(**kwargs)
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 96, in _wrapper
    report = dict(children=list(map(str, data)))
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 598, in __call__
    for run_dir in self._execute(**kwargs):
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 642, in _execute
    for attempt in attempt(**kwargs):
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 156, in _call_without_report
    child_obj(**kwargs)
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 817, in _wrap
    mdriver(**kwargs)
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 94, in _wrapper
    data = func(*args, **kwargs)
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/driver.py", line 701, in __call__
    run_metrics = extractor.extract(self.report.get('metas'))
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/api.py", line 121, in extract
    metrics = self.extract_metrics(metas)
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/benchmark/osu.py", line 47, in extract_metrics
    return self.epilog()
  File "/nix/store/bywlyagvy4my2qwfvhkaqq75aiklz2qz-hpcbench-DEV_ENV/lib/python3.6/site-packages/hpcbench/benchmark/osu.py", line 178, in epilog
    minb_lat_b, minb_lat = self.s_raw_data[0]
IndexError: list index out of range
```

@tristan0x is this related to the changes in the srun data writing?

**Comment by tristan0x** [comment]
Probably. Can you please share reproducible scenario?

**Comment by tristan0x** [comment]
I managed to reproduce the issue @ohm314 
osu hpcbench benchmark assumes output is always present. But in a srun context with several processes, only rank 0 is writing them to standard output.
I am updating osu benchmark accordingly.

**Comment by ohm314** [comment]
checkout the bench/minigemm branch in the test_ci setup, then run the CI runner script. You can use this campaign file:

```
output_dir: hpcbench-osu-%Y%m%d-%H%M%S

network:
    nodes:
      - tds0[1-8]
    tags:
      uc1:
        nodes:
        - tds01
        - tds02
      uc2:
        nodes:
        - tds03
        - tds04
      uc3:
        nodes:
        - tds05
        - tds06
      uc4:
        nodes:
        - tds07
        - tds08
      uc5:
        tags: [uc1, uc2, uc3, uc4]
      knl:
        tags: [uc1]
      skylake:
        tags: [uc2, uc3, uc4]
      gpu:
        tags: [uc2]
      nvme:
        tags: [uc4]

process:
  type: slurm
  sbatch:
    # constraint: "cpu"
    account: proj16
    time: 01:00:00
    qos: bigjob
    mem: 64g
    partition: prod
    hint: memory_bound
  sbatch_template: |
    #!/bin/bash
    {%- for opt in sbatch_arguments %}
    #SBATCH {{opt}}
    {%- endfor %}
    module purge
    module load nix/mvapich2-rdma
    module load nix/bench/stream
    module load nix/osu-mpi-bench
    echo "SLURM_NTASKS: $$SLURM_NTASKS" 
    echo "SLURM_NTASKS_PER_NODE: $$SLURM_NTASKS_PER_NODE"
    echo "SLURM_NODELIST: $$SLURM_NODELIST"
    {{ hpcbench_command }}

benchmarks:
  uc1:
    sbatch:
      nodes: 2
    osu:
      type: osu
      srun:
        mpi: pmi2
      attributes:
        categories: [osu_allgather, osu_allgatherv]
  uc3:
    sbatch:
      nodes: 2
    osu:
      type: osu
      srun:
        mpi: pmi2
      attributes:
        categories: [osu_allgather, osu_allgatherv]
  uc4:
    sbatch:
      nodes: 2
    osu:
      type: osu
      srun:
        mpi: pmi2
      attributes:
        categories: [osu_allgather, osu_allgatherv]
```
